Test/budget/js
econominhas/backend pull request #37
Opened 2024-03-01 01:07 UTC by ganes369

tests: Add tests for budget-related use cases

Add unit and integration tests for use cases related to the budget module. This includes testing for creating a budget, getting or creating budget dates, creating a basic budget with items, budget overview, and creating future budget dates.

- Tests to create a successful budget
- Tests to handle exceptions when creating a budget fails
- Tests to create a budget with the maximum number of months
- Tests to create new budget dates
- Tests to create a basic budget with items
- Tests for the budget overview
- Tests to create future budget dates

Each test validates the different scenarios and expected behaviors of budget-related use cases, ensuring the robustness and reliability of the code.

2024-03-11 22:53 UTC, henriqueleite42 requested changes
O review nao foi feito em 100% do arquivo devido a quantidade necessária de correcoes:
- Revisar os comentários para garantir que sao realmente necessários ou o codigo se descreve sozinho
- Escrever os comentarios que sao necessários em ingles
- Remover `spyOn` e seguir o padrao dos outros testes

2024-03-11 22:53 UTC, henriqueleite42 commented on tests/src/usecases/budget.spec.ts
> +			const spyOn1 = jest.spyOn(accountService.mock, 'setBudget');
Nao usar `spyOn`, seguir o padrao dos outros testes

2024-03-11 22:53 UTC, henriqueleite42 commented on tests/src/usecases/budget.spec.ts
> +				.spyOn(budgetRepository.mock, 'createWithItems')
Nao usar `spyOn`, seguir o padrao dos outros testes

2024-03-11 22:53 UTC, henriqueleite42 commented on tests/src/usecases/budget.spec.ts
> +		it('deve criar um orçamento com o limite máximo de meses', async () => {
Escrever sempre em ingles

2024-03-11 22:53 UTC, henriqueleite42 commented on tests/mocks/repositories/postgres/budget.ts
> +			id: '1',
Cada output deve serguir o padrao:
```
const outputs = {
  [nome da funcao]: {
    [caso em que o output é retornado, ex: sucess, empty]: [output]
  }
}
```

2024-03-11 22:53 UTC, henriqueleite42 commented on tests/mocks/repositories/postgres/category.ts
> +		getByUser: [
Cada output deve serguir o padrao:
```
const outputs = {
  [nome da funcao]: {
    [caso em que o output é retornado, ex: sucess, empty]: [output]
  }
}
```

2024-03-11 22:53 UTC, henriqueleite42 commented on tests/mocks/repositories/postgres/transaction.ts
> +			{
Cada output deve serguir o padrao:
```
const outputs = {
  [nome da funcao]: {
    [caso em que o output é retornado, ex: sucess, empty]: [output]
  }
}
```

2024-03-11 22:53 UTC, henriqueleite42 commented on tests/src/usecases/budget.spec.ts
> +			// Verifique se o orçamento foi criado corretamente
Sempre escrever em ingles.
Nesse caso o comentário é desnecessario, remover.

2024-03-11 22:53 UTC, henriqueleite42 commented on tests/src/usecases/budget.spec.ts
> +			// Simular falha ao criar o orçamento
Sempre escrever em ingles

2024-03-11 22:53 UTC, henriqueleite42 commented on tests/src/usecases/budget.spec.ts
> +			// Simular chamada ao método setBudget do serviço de conta
// desnecessário, remover

2024-03-11 22:53 UTC, henriqueleite42 commented on tests/src/usecases/budget.spec.ts
> +			// Chamar o método create e capturar a exceção
// desnecessário, remover

2024-03-11 22:53 UTC, henriqueleite42 commented on tests/src/usecases/budget.spec.ts
> +			// Verificar se uma exceção foi lançada
// desnecessário, remover

2024-03-11 22:53 UTC, henriqueleite42 commented on tests/src/usecases/budget.spec.ts
> +			// Defina o limite máximo de meses
// desnecessário, remover

2024-03-11 22:53 UTC, henriqueleite42 commented on tests/src/usecases/budget.spec.ts
> +			const itemsFormatted = input.items
Usado apenas uma vez, ao inves de definir a variavel, definir direto como o valor

2024-03-11 22:53 UTC, henriqueleite42 commented on tests/src/usecases/budget.spec.ts
> +				{ categoryId: 2, amount: 0 }, // Despesa zero
Sempre escrever em ingles

2024-03-12 13:58 UTC, ganes369 commented on tests/src/usecases/budget.spec.ts
> +			const itemsFormatted = input.items
![image](https://github.com/econominhas/backend/assets/33840492/4d7e34c0-3266-48ab-912a-96efed7141e2)
dessa forma?

2024-03-15 11:08 UTC, henriqueleite42 requested changes

2024-03-15 11:08 UTC, henriqueleite42 commented on tests/src/usecases/budget.spec.ts
> +			expect(result.remainingBudget).toEqual(300);
```suggestion
			expect(result).toMatchObject({
			  totalBudget: 450,
			  totalExpenses: 150,
			  remainingBudget: 300,
			});
```

2024-03-15 11:08 UTC, henriqueleite42 commented on tests/src/usecases/budget.spec.ts
> +			expect(result.remainingBudget).toEqual(-130);
```suggestion
			expect(result).toMatchObject({
			  totalBudget: 120,
			  totalExpenses: 250,
			  remainingBudget: -130,
			});
```

2024-03-15 11:08 UTC, henriqueleite42 commented on tests/src/usecases/budget.spec.ts
> +		});
Also add the validation for `budgetByCategory`

2024-03-15 11:08 UTC, henriqueleite42 commented on tests/src/usecases/budget.spec.ts
> +			const dates = Array.from({ length: input.amount }, (_, index) => {
Use raw values or simple logic instead of a bit more complex logic, or else we would have to test it too.

2024-03-15 23:52 UTC, henriqueleite42 approved these changes

2024-03-15 23:53 UTC, merged